services:

  app.session.storage:
    class: AppBundle\Shop\Storage\SessionStorage
    arguments: ["@session"]

  app.cart:
    class: AppBundle\Shop\Cart
    arguments: ["@app.session.storage"]

  twig.substrws.extension:
    class: AppBundle\Twig\substrwsExtension
    tags:
      - { name: twig.extension }

  twig.istrunc.extension:
    class: AppBundle\Twig\isTruncExtensions
    tags:
      - { name: twig.extension }